[theme]
base="light"
[global]
disableWatchdogWarning = true
[runner]
fastReruns = true
[server]
maxUploadSize = 500
maxMessageSize = 500
port = 8080
[browser]
serverAddress = "localhost"
serverPort = 8080